"""Genera una imagen PNG de ejemplo con metadatos de IA REALES incrustados (chunks tEXt).

Sirve para probar el backend clic a clic: `identify` debe detectar la procedencia y `metadata`
debe borrarla. Uso: `python -m tools.make_sample salida.png`.
"""
from __future__ import annotations

import sys
from io import BytesIO
from pathlib import Path

from PIL import Image, PngImagePlugin

_TEXT = {
    "Software": "DemoDiffusion 1.5",
    "parameters": "a scenic mountain landscape at dusk, cfg scale: 7, steps: 30, sampler: Euler a, seed: 4412, Model: sd-demo",
    "Comment": "Generated by Example-AI. Content Credentials: contentauthenticity.org (C2PA demo claim)",
    "Author": "MUESTRA - contenido de ejemplo (no subas nada ajeno para probar)",
}


def _base_image(w: int = 512, h: int = 320) -> Image.Image:
    img = Image.new("RGB", (w, h))
    px = img.load()
    for y in range(h):
        for x in range(w):
            px[x, y] = ((40 + x * 160 // w) & 255, (60 + y * 140 // h) & 255, 150)
    return img


def make_sample_bytes() -> bytes:
    meta = PngImagePlugin.PngInfo()
    for k, v in _TEXT.items():
        meta.add_text(k, v)
    buf = BytesIO()
    _base_image().save(buf, format="PNG", pnginfo=meta)
    return buf.getvalue()


def make_sample(path: str | Path) -> Path:
    p = Path(path)
    p.write_bytes(make_sample_bytes())
    return p


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "sample.png"
    print("escrito:", make_sample(out))
